name: uptimekuma

services:
  uptime-kuma:
    image: louislam/uptime-kuma:2.5.4@sha256:917318f9d7be5257f43ba412c766a473be336eb451d70744f3b482d0c3997c0e
    volumes:
      - uptime-kuma-data:/app/data
    ports:
      - 3001:3001
    restart: unless-stopped

volumes:
  uptime-kuma-data:
