services:
  vaultwarden:
    image: vaultwarden/server:1.33.2
    container_name: vaultwarden
    restart: always
    environment:
      DOMAIN: ${DOMAIN} # required when using a reverse proxy; your domain; vaultwarden needs to know it's https to work properly with attachments
      SMTP_HOST: ${SMTP_HOST}
      SMTP_FROM: ${SMTP_FROM}
      SMTP_PORT: 465
      SMTP_SECURITY: "force_tls"
      SMTP_USERNAME: ${SMTP_USERNAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      SIGNUPS_ALLOWED: ${SIGNUPS_ALLOWED} # Deactivate this with "false" after you have created your account so that no strangers can register
    volumes:
      - vaultdata:/data # the path before the : can be changed
    ports:
      - 11001:80 # you can replace the 11001 with your preferred port

volumes:
  vaultdata:
