services:
  vaultwarden:
    image: vaultwarden/server:1.34.1
    container_name: vaultwarden
    restart: always
    environment:
      DOMAIN: ${DOMAIN} # required when using a reverse proxy; your domain; vaultwarden needs to know it's https to work properly with attachments
      SMTP_HOST: ${SMTP_HOST}
      SMTP_FROM: ${SMTP_FROM}
      SMTP_PORT: 587
      SMTP_SECURITY: "starttls"
      SMTP_USERNAME: ${SMTP_USERNAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      SIGNUPS_ALLOWED: ${SIGNUPS_ALLOWED} # Deactivate this with "false" after you have created your account so that no strangers can register
    volumes:
      - vaultdata:/data # the path before the : can be changed
    ports:
      - 11001:80 # you can replace the 11001 with your preferred port

  backup:
    image: ttionya/vaultwarden-backup:latest
    restart: always
    environment:
      RCLONE_REMOTE_NAME: "vaultwardenbackup"
      RCLONE_REMOTE_DIR: "/vaultwardenbackup/"
      PING_URL_WHEN_SUCCESS: ${PING_URL_WHEN_SUCCESS}
      TIMEZONE: "ICT"
    volumes:
      - vaultdata:/bitwarden/data/
      - vaultwarden-rclone-data:/config/

volumes:
  vaultdata:
  vaultwarden-rclone-data:
    external: true
    name: vaultwarden-rclone-data
